#!/bin/bash
# PreToolUse hook (Edit|Write|NotebookEdit): blocks edits inside this
# project's build-output directories. All of these are gitignored and
# regenerated by their respective build systems -- a hand-edit there is
# silently discarded on the next build.
set -euo pipefail

input="$(cat)"
file_path="$(echo "$input" | jq -r '.tool_input.file_path // .tool_input.notebook_path // empty')"

if [ -z "$file_path" ]; then
  exit 0
fi

rel="${file_path#"$PWD"/}"

case "$rel" in
  build/*|build_rp2040_pico/*|build_rp2040_pico_w/*|build_rp2040_pico2/*|build_rp2040_pico2_w/*|build_rp2040_smk_kbd_rp2040/*|build_nrf52840/*|build_stm32f4/*|build_stm32wb/*|.build/*)
    reason="'$rel' is inside a build output directory, which is gitignored and regenerated by the build -- edits there are silently discarded on the next build/flash. Edit the real source instead (Sources/, ports/, main/, or the relevant board's platform/ directory)."
    jq -n --arg reason "$reason" '{
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "deny",
        permissionDecisionReason: $reason
      }
    }'
    ;;
esac
