#!/bin/bash
# PreToolUse hook (Edit|Write): asks for confirmation before directly
# editing the ESP-IDF-generated `sdkconfig` file. It's gitignored and
# meant to be a local, ephemeral build config -- `sdkconfig.defaults`
# is the tracked source of truth changes should normally flow through.
set -euo pipefail

input="$(cat)"
file_path="$(echo "$input" | jq -r '.tool_input.file_path // empty')"

if [ -z "$file_path" ]; then
  exit 0
fi

base="$(basename "$file_path")"

if [ "$base" = "sdkconfig" ]; then
  reason="sdkconfig is gitignored and regenerated by ESP-IDF from sdkconfig.defaults -- a direct edit here won't survive a clean rebuild and won't be shared with anyone else who builds this project. If this change should stick, consider adding it to sdkconfig.defaults instead. Proceed with editing sdkconfig directly anyway?"
  jq -n --arg reason "$reason" '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "ask",
      permissionDecisionReason: $reason
    }
  }'
fi
