#!/usr/bin/env bash
# Regenerates the BLE upload service's UUID constants for both repos from
# ble_upload_uuids.json. Run after changing that file; commit the outputs in
# both repos.
#
#   ./generate_ble_uuids.sh [path-to-smk_configurator]   (default ../smk_configurator)
set -euo pipefail
cd "$(dirname "$0")"
CONFIGURATOR="${1:-../smk_configurator}"

python3 - "$CONFIGURATOR" <<'PY'
import json, pathlib, sys

configurator = pathlib.Path(sys.argv[1]).expanduser()
uuids = json.load(open("ble_upload_uuids.json"))

def nimble_bytes(uuid: str) -> str:
    raw = uuid.replace("-", "")
    octets = [raw[i:i + 2] for i in range(0, 32, 2)]
    body = ", ".join("0x" + o.lower() for o in reversed(octets))
    return ",\n                     ".join(
        [", ".join(body.split(", ")[i:i + 8]) for i in range(0, 16, 8)]
    )

names = {
    "service": "smk_upload_svc_uuid",
    "packet": "smk_upload_packet_chr_uuid",
    "response": "smk_upload_response_chr_uuid",
}

header = ["// Generated by generate_ble_uuids.sh from ble_upload_uuids.json.",
          "// Do not edit by hand -- edit the JSON and re-run the script.",
          "#pragma once",
          "",
          '#include "host/ble_uuid.h"',
          ""]
for role, name in names.items():
    header.append(f"// {uuids[role]}")
    header.append(f"static const ble_uuid128_t {name} =")
    header.append(f"    BLE_UUID128_INIT({nimble_bytes(uuids[role])});")
    header.append("")
pathlib.Path("Sources/components/smk_ble_uuids.h").write_text("\n".join(header))

swift = ["// Generated by ~/esp/SMK/generate_ble_uuids.sh from",
         "// ble_upload_uuids.json. Do not edit by hand.",
         "",
         "#if canImport(CoreBluetooth)",
         "import CoreBluetooth",
         "",
         "/// UUIDs of the firmware's custom keymap-upload GATT service.",
         "enum BLEUploadUUIDs {",
         f'    static var service: CBUUID {{ CBUUID(string: "{uuids["service"]}") }}',
         f'    static var packet: CBUUID {{ CBUUID(string: "{uuids["packet"]}") }}',
         f'    static var response: CBUUID {{ CBUUID(string: "{uuids["response"]}") }}',
         "}",
         "#endif",
         ""]
out = configurator / "Sources/SMKConfigurator/Device/BLEUploadUUIDs.swift"
out.write_text("\n".join(swift))
print(f"wrote Sources/components/smk_ble_uuids.h and {out}")
PY
