#!/usr/bin/env bash
# Compiles keymap.json to the binary payload format `decodeKeymapPayload`
# (Sources/SMKCore/KeymapBinary.swift) decodes, and emits it as a Swift byte
# array literal -- so the compiled-in default keymap boots without cJSON.
# Run after changing keymap.json; commit the regenerated
# Sources/SMKCore/DefaultKeymapGenerated.swift.
#
# See docs/superpowers/specs/2026-08-21-binary-keymap-format-design.md for
# the payload layout this produces.
#
#   ./generate_default_keymap.sh
set -euo pipefail
cd "$(dirname "$0")"

python3 - <<'PY'
import json, pathlib

manifest = json.load(open("keycodes.json"))
usage_by_token = {e["token"]: e["usage"] for e in manifest["keyboard"]}

# Fixed USB HID modifier bitmask -- Modifier.rawValue in
# Sources/SMKCore/Modifier.swift, bits 0-7 LSB first. This is a stable USB
# HID/report convention, not part of the generated key vocabulary, so
# (unlike `key:` usages) it is not derived from keycodes.json.
modifier_bits = {
    "leftCtrl": 0x01, "leftShift": 0x02, "leftAlt": 0x04, "leftGUI": 0x08,
    "rightCtrl": 0x10, "rightShift": 0x20, "rightAlt": 0x40, "rightGUI": 0x80,
}

# KeymapCellTag's raw values (KeymapBinary.swift) -- the wire format's tag
# byte. Renumbering these here without also updating that enum breaks every
# firmware build silently (Package.swift globs SMKCore; only the six
# CMakeLists and this generator would still agree with each other, not with
# the decoder).
TAG_NONE, TAG_KEY, TAG_MOD, TAG_MO, TAG_TG, TAG_TRANS, TAG_TOGGLE_CONN, TAG_MACRO = range(8)


def encode_cell(token):
    if token == "none":
        return (TAG_NONE, 0)
    if token in ("trans", "transparent"):
        return (TAG_TRANS, 0)
    if token == "toggle_conn":
        return (TAG_TOGGLE_CONN, 0)
    if token.startswith("key:"):
        name = token[4:]
        if name not in usage_by_token:
            raise SystemExit("unknown key token in keymap.json: %r" % token)
        return (TAG_KEY, usage_by_token[name])
    if token.startswith("mod:"):
        name = token[4:]
        if name not in modifier_bits:
            raise SystemExit("unknown modifier token in keymap.json: %r" % token)
        return (TAG_MOD, modifier_bits[name])
    if token.startswith("mo:"):
        return (TAG_MO, int(token[3:]))
    if token.startswith("tg:"):
        return (TAG_TG, int(token[3:]))
    if token.startswith("macro:"):
        return (TAG_MACRO, int(token[6:]))
    raise SystemExit("unrecognized keymap cell token in keymap.json: %r" % token)


keymap_json_text = open("keymap.json").read()
keymap = json.loads(keymap_json_text)
matrix = keymap["matrix"]
rows = matrix["rows"]
cols = matrix["cols"]
cols_are_driven = 1 if matrix["colsAreDriven"] else 0
layers = keymap["layers"]

row_count = len(rows)
col_count = len(cols)
layer_count = len(layers)
macro_count = 0  # keymap.json carries no macros today; the format reserves the byte.

for li, layer in enumerate(layers):
    if len(layer) != row_count:
        raise SystemExit("layer %d has %d rows, matrix declares %d" % (li, len(layer), row_count))
    for ri, row in enumerate(layer):
        if len(row) != col_count:
            raise SystemExit("layer %d row %d has %d cols, matrix declares %d" % (li, ri, len(row), col_count))

for name, value in (("rowCount", row_count), ("colCount", col_count),
                    ("layerCount", layer_count), ("macroCount", macro_count)):
    if not (0 <= value <= 0xFF):
        raise SystemExit("%s=%d does not fit in the format's one-byte header field" % (name, value))
for name, pins in (("row", rows), ("col", cols)):
    for pin in pins:
        if not (0 <= pin <= 0xFF):
            raise SystemExit("%s pin %d does not fit in one byte" % (name, pin))

payload = bytearray()
payload += bytes([row_count, col_count, cols_are_driven, layer_count, macro_count, 0])  # reserved=0
payload += bytes(rows)
payload += bytes(cols)
for layer in layers:
    for row in layer:
        for token in row:
            tag, param = encode_cell(token)
            if not (0 <= param <= 0xFF):
                raise SystemExit("cell %r encodes a parameter that doesn't fit in one byte" % token)
            payload += bytes([tag, param])

BANNER = ["// Generated by generate_default_keymap.sh from keymap.json.",
          "// Do not edit by hand -- edit keymap.json and re-run the script.",
          ""]

lines = list(BANNER)
lines += [
    "/// The compiled-in default keymap, pre-encoded in the same binary payload",
    "/// format `decodeKeymapPayload` (KeymapBinary.swift) decodes from an",
    "/// uploaded or stored keymap -- so the boot path loads it without parsing",
    "/// any JSON. See",
    "/// docs/superpowers/specs/2026-08-21-binary-keymap-format-design.md for the",
    "/// byte layout.",
    "let defaultKeymapBytes: [UInt8] = [",
]
bytes_per_line = 16
for i in range(0, len(payload), bytes_per_line):
    chunk = payload[i:i + bytes_per_line]
    lines.append("    " + ", ".join(str(b) for b in chunk) + ",")
lines += ["]", ""]

out = pathlib.Path("Sources/SMKCore/DefaultKeymapGenerated.swift")
out.write_text("\n".join(lines))
print("wrote %s (%d bytes binary vs %d bytes of keymap.json)" %
      (out, len(payload), len(keymap_json_text)))
PY
