// Generated by generate_default_keymap.sh from keymap.json.
// Do not edit by hand -- edit keymap.json and re-run the script.

/// The compiled-in default keymap, pre-encoded in the same binary payload
/// format `decodeKeymapPayload` (KeymapBinary.swift) decodes from an
/// uploaded or stored keymap -- so the boot path loads it without parsing
/// any JSON. See
/// docs/superpowers/specs/2026-08-21-binary-keymap-format-design.md for the
/// byte layout.
let defaultKeymapBytes: [UInt8] = [
    5, 12, 1, 2, 0, 0, 0, 1, 2, 3, 5, 6, 7, 8, 14, 15,
    18, 19, 20, 21, 22, 23, 17, 1, 30, 1, 31, 1, 32, 1, 33, 1,
    34, 1, 35, 1, 36, 1, 37, 1, 38, 1, 39, 1, 45, 1, 42, 1,
    43, 1, 20, 1, 26, 1, 8, 1, 21, 1, 23, 1, 28, 1, 24, 1,
    12, 1, 18, 1, 19, 1, 49, 1, 41, 1, 4, 1, 22, 1, 7, 1,
    9, 1, 10, 1, 11, 1, 13, 1, 14, 1, 15, 1, 51, 1, 40, 2,
    2, 1, 29, 1, 27, 1, 6, 1, 25, 1, 5, 1, 17, 1, 16, 1,
    54, 1, 55, 1, 56, 2, 32, 2, 1, 2, 8, 2, 4, 3, 1, 2,
    2, 1, 44, 0, 0, 2, 32, 3, 1, 2, 64, 2, 128, 2, 16, 6,
    0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5,
    0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5,
    0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5,
    0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 1, 80, 1, 81, 1,
    82, 1, 79, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5,
    0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5,
    0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 0, 0, 5, 0, 5,
    0, 5, 0, 5, 0, 5, 0,
]
