// Generated by generate_keycodes.sh from keycodes.json.
// Do not edit by hand -- edit the JSON and re-run the script.

// Host-only: strcmp comes from the bridging header (newlib) on embedded
// builds; the host SMKCore build needs it imported explicitly.
#if canImport(Darwin)
import Darwin
#elseif canImport(Glibc)
import Glibc
#endif

// Keycodes based on HID standards.
enum KeyCode: UInt8 {
    case noKey
    case a
    case b
    case c
    case d
    case e
    case f
    case g
    case h
    case i
    case j
    case k
    case l
    case m
    case n
    case o
    case p
    case q
    case r
    case s
    case t
    case u
    case v
    case w
    case x
    case y
    case z
    case k1
    case k2
    case k3
    case k4
    case k5
    case k6
    case k7
    case k8
    case k9
    case k0
    case enter
    case escape
    case backspace
    case tab
    case space
    case minus
    case equal
    case leftBracket
    case rightBracket
    case backslash
    case semicolon
    case quote
    case grave
    case comma
    case period
    case slash
    case capsLock
    case f1
    case f2
    case f3
    case f4
    case f5
    case f6
    case f7
    case f8
    case f9
    case f10
    case f11
    case f12
    case printScreen
    case scrollLock
    case pause
    case home
    case pageUp
    case delete
    case end
    case pageDown
    case leftArrow
    case rightArrow
    case upArrow
    case downArrow
    case application
    case transparent // Like QMK's KC_TRNS

    // Explicit rawValue overriding the synthesized ordinals: these are real
    // HID usage IDs, which is what HIDReport.addKey puts on the wire. Note the
    // synthesized init?(rawValue:) is therefore inconsistent (it maps from
    // ordinals) and must stay unused -- see the design doc's Risks section.
    var rawValue: UInt8 {
        switch self {
        case .noKey: return 0x00
        case .a: return 0x04
        case .b: return 0x05
        case .c: return 0x06
        case .d: return 0x07
        case .e: return 0x08
        case .f: return 0x09
        case .g: return 0x0A
        case .h: return 0x0B
        case .i: return 0x0C
        case .j: return 0x0D
        case .k: return 0x0E
        case .l: return 0x0F
        case .m: return 0x10
        case .n: return 0x11
        case .o: return 0x12
        case .p: return 0x13
        case .q: return 0x14
        case .r: return 0x15
        case .s: return 0x16
        case .t: return 0x17
        case .u: return 0x18
        case .v: return 0x19
        case .w: return 0x1A
        case .x: return 0x1B
        case .y: return 0x1C
        case .z: return 0x1D
        case .k1: return 0x1E
        case .k2: return 0x1F
        case .k3: return 0x20
        case .k4: return 0x21
        case .k5: return 0x22
        case .k6: return 0x23
        case .k7: return 0x24
        case .k8: return 0x25
        case .k9: return 0x26
        case .k0: return 0x27
        case .enter: return 0x28
        case .escape: return 0x29
        case .backspace: return 0x2A
        case .tab: return 0x2B
        case .space: return 0x2C
        case .minus: return 0x2D
        case .equal: return 0x2E
        case .leftBracket: return 0x2F
        case .rightBracket: return 0x30
        case .backslash: return 0x31
        case .semicolon: return 0x33
        case .quote: return 0x34
        case .grave: return 0x35
        case .comma: return 0x36
        case .period: return 0x37
        case .slash: return 0x38
        case .capsLock: return 0x39
        case .f1: return 0x3A
        case .f2: return 0x3B
        case .f3: return 0x3C
        case .f4: return 0x3D
        case .f5: return 0x3E
        case .f6: return 0x3F
        case .f7: return 0x40
        case .f8: return 0x41
        case .f9: return 0x42
        case .f10: return 0x43
        case .f11: return 0x44
        case .f12: return 0x45
        case .printScreen: return 0x46
        case .scrollLock: return 0x47
        case .pause: return 0x48
        case .home: return 0x4A
        case .pageUp: return 0x4B
        case .delete: return 0x4C
        case .end: return 0x4D
        case .pageDown: return 0x4E
        case .leftArrow: return 0x50
        case .rightArrow: return 0x4F
        case .upArrow: return 0x52
        case .downArrow: return 0x51
        case .application: return 0x65
        case .transparent: return 0xFF
        }
    }

    // A generated if-chain rather than a lookup table: a global
    // array-of-tuples needs runtime lazy initialization under Embedded Swift,
    // and this file compiles flat into six embedded targets that cannot be
    // built or flashed from a dev machine. Generated length costs nothing to
    // maintain, so the boilerplate the table would have saved is not a cost.
    static func fromCString(_ cStr: UnsafePointer<Int8>) -> KeyCode {
        if strcmp(cStr, "a") == 0 { return .a }
        if strcmp(cStr, "b") == 0 { return .b }
        if strcmp(cStr, "c") == 0 { return .c }
        if strcmp(cStr, "d") == 0 { return .d }
        if strcmp(cStr, "e") == 0 { return .e }
        if strcmp(cStr, "f") == 0 { return .f }
        if strcmp(cStr, "g") == 0 { return .g }
        if strcmp(cStr, "h") == 0 { return .h }
        if strcmp(cStr, "i") == 0 { return .i }
        if strcmp(cStr, "j") == 0 { return .j }
        if strcmp(cStr, "k") == 0 { return .k }
        if strcmp(cStr, "l") == 0 { return .l }
        if strcmp(cStr, "m") == 0 { return .m }
        if strcmp(cStr, "n") == 0 { return .n }
        if strcmp(cStr, "o") == 0 { return .o }
        if strcmp(cStr, "p") == 0 { return .p }
        if strcmp(cStr, "q") == 0 { return .q }
        if strcmp(cStr, "r") == 0 { return .r }
        if strcmp(cStr, "s") == 0 { return .s }
        if strcmp(cStr, "t") == 0 { return .t }
        if strcmp(cStr, "u") == 0 { return .u }
        if strcmp(cStr, "v") == 0 { return .v }
        if strcmp(cStr, "w") == 0 { return .w }
        if strcmp(cStr, "x") == 0 { return .x }
        if strcmp(cStr, "y") == 0 { return .y }
        if strcmp(cStr, "z") == 0 { return .z }
        if strcmp(cStr, "1") == 0 { return .k1 }
        if strcmp(cStr, "2") == 0 { return .k2 }
        if strcmp(cStr, "3") == 0 { return .k3 }
        if strcmp(cStr, "4") == 0 { return .k4 }
        if strcmp(cStr, "5") == 0 { return .k5 }
        if strcmp(cStr, "6") == 0 { return .k6 }
        if strcmp(cStr, "7") == 0 { return .k7 }
        if strcmp(cStr, "8") == 0 { return .k8 }
        if strcmp(cStr, "9") == 0 { return .k9 }
        if strcmp(cStr, "0") == 0 { return .k0 }
        if strcmp(cStr, "enter") == 0 { return .enter }
        if strcmp(cStr, "escape") == 0 { return .escape }
        if strcmp(cStr, "backspace") == 0 { return .backspace }
        if strcmp(cStr, "tab") == 0 { return .tab }
        if strcmp(cStr, "space") == 0 { return .space }
        if strcmp(cStr, "minus") == 0 { return .minus }
        if strcmp(cStr, "equal") == 0 { return .equal }
        if strcmp(cStr, "leftBracket") == 0 { return .leftBracket }
        if strcmp(cStr, "rightBracket") == 0 { return .rightBracket }
        if strcmp(cStr, "backslash") == 0 { return .backslash }
        if strcmp(cStr, "semicolon") == 0 { return .semicolon }
        if strcmp(cStr, "quote") == 0 { return .quote }
        if strcmp(cStr, "grave") == 0 { return .grave }
        if strcmp(cStr, "comma") == 0 { return .comma }
        if strcmp(cStr, "period") == 0 { return .period }
        if strcmp(cStr, "slash") == 0 { return .slash }
        if strcmp(cStr, "capsLock") == 0 { return .capsLock }
        if strcmp(cStr, "f1") == 0 { return .f1 }
        if strcmp(cStr, "f2") == 0 { return .f2 }
        if strcmp(cStr, "f3") == 0 { return .f3 }
        if strcmp(cStr, "f4") == 0 { return .f4 }
        if strcmp(cStr, "f5") == 0 { return .f5 }
        if strcmp(cStr, "f6") == 0 { return .f6 }
        if strcmp(cStr, "f7") == 0 { return .f7 }
        if strcmp(cStr, "f8") == 0 { return .f8 }
        if strcmp(cStr, "f9") == 0 { return .f9 }
        if strcmp(cStr, "f10") == 0 { return .f10 }
        if strcmp(cStr, "f11") == 0 { return .f11 }
        if strcmp(cStr, "f12") == 0 { return .f12 }
        if strcmp(cStr, "printScreen") == 0 { return .printScreen }
        if strcmp(cStr, "scrollLock") == 0 { return .scrollLock }
        if strcmp(cStr, "pause") == 0 { return .pause }
        if strcmp(cStr, "home") == 0 { return .home }
        if strcmp(cStr, "pageUp") == 0 { return .pageUp }
        if strcmp(cStr, "delete") == 0 { return .delete }
        if strcmp(cStr, "end") == 0 { return .end }
        if strcmp(cStr, "pageDown") == 0 { return .pageDown }
        if strcmp(cStr, "left") == 0 { return .leftArrow }
        if strcmp(cStr, "right") == 0 { return .rightArrow }
        if strcmp(cStr, "up") == 0 { return .upArrow }
        if strcmp(cStr, "down") == 0 { return .downArrow }
        if strcmp(cStr, "application") == 0 { return .application }
        return .noKey
    }
}
