// ESP32-C6 BLE HID glue — full Swift port of the former
// Sources/components/ble_helper.c (now deleted).
//
// The final round of this port moved the struct construction over too:
// Bridging.h imports host/ble_hs.h, host/ble_hs_mbuf.h, services/gap/
// ble_svc_gap.h, nimble/nimble_port.h, nvs_flash.h and smk_ble_uuids.h, so
// `struct ble_hs_adv_fields` and the global `struct ble_hs_cfg` — both
// genuinely bitfield-heavy — come across as real ClangImporter types whose
// bitfield members are computed properties with header-derived packing, and
// the GATT service/characteristic definition tables are built from the
// imported `ble_gatt_svc_def`/`ble_gatt_chr_def` types. Nothing here
// mirrors a layout by hand. Same for esp_hid_device_config_t/
// esp_hid_raw_report_map_t (esp_hidd.h, imported all along).
//
// Keymap upload rides a custom GATT service (write characteristic in,
// notify characteristic back), NOT a HID Report ID 2 channel — macOS hides
// the HID service (0x1812) from Core Bluetooth apps entirely, so a HID
// vendor report was unreachable from the configurator. See
// smk_configurator/docs/superpowers/specs/2026-08-15-ble-custom-gatt-upload-design.md
// and Sources/components/smk_ble_uuids.h (generated by
// generate_ble_uuids.sh) for the three UUIDs.
//
// Buffer lifetimes: esp_hidd_dev_init(), NimBLE's GATT registration, and
// the advertiser keep pointers into the report map, the name strings, the
// UUIDs, and the service-definition tables past the call, so all of those
// live in permanently-allocated storage (deliberate leak, matching the C
// original's `static const` arrays) — same pattern as
// ports/common/BleHidGatt.swift's permanentCopy.
//
// hidDev ownership: init_ble_hid() below receives esp_hidd_dev_init()'s
// out-param directly into `hidDev`, the single source of truth every other
// function here reads.

#if canImport(Darwin)
import Darwin
#elseif canImport(Glibc)
import Glibc
#endif

// Reuses the exact fixed-2-arg @_extern(c, "printf") binding
// ports/rp2040/PlatformConfig.swift's kb_log already established for
// Task 3, rather than inventing a second variadic-printf approach for
// this target. ESP32-C6's kb_log predates any Swift version (it lived
// only in ble_helper.c as an ESP_LOGI wrapper), so this task is the one
// that ports it — nothing upstream already claimed it.
@_extern(c, "printf")
func printf(_ format: UnsafePointer<CChar>, _ arg: UnsafePointer<CChar>) -> Int32

func kb_log(_ msg: UnsafePointer<CChar>) {
    _ = printf("[SMK] %s\n", msg)
}

// esp_hidd_dev_connected/esp_hidd_dev_input_set/esp_hidd_dev_battery_set:
// no @_extern redeclarations here — Bridging.h already `#include`s
// esp_hidd.h, so these are called via their real, ClangImporter-imported
// declarations instead. A hand-copied @_extern redeclaration would shadow
// those (same hazard Bridging.h itself already calls out for
// init_wired_link/send_wired_report elsewhere) and could silently drift
// out of sync with the real signature on a future ESP-IDF upgrade. The
// opaque `esp_hidd_dev_t *` C type imports as `OpaquePointer` — see
// `hidDev` below — and `size_t` params import as `Int`.

// nimble_port_run / nimble_port_freertos_deinit / esp_nimble_enable all
// come in via Bridging.h's nimble_port.h + nimble_port_freertos.h imports;
// the ble_gatts_*/ble_gap_*/ble_hs_mbuf_* calls below via ble_hs.h and
// ble_hs_mbuf.h.

// ---------------------------------------------------------------------------
// Device identity + HID report map (formerly ble_helper.c's statics)
// ---------------------------------------------------------------------------

// HID Report Map: a standard keyboard (Report ID 1). Keymap upload used to
// ride a second, vendor-defined Report ID 2 channel here; that's gone now —
// macOS hides the HID service from Core Bluetooth apps entirely, so it was
// unreachable from the configurator. Upload moved to the custom GATT
// service registered in init_ble_hid() below.
private let hidReportMapBytes: [UInt8] = [
    0x05, 0x01, 0x09, 0x06, 0xa1, 0x01, 0x85, 0x01, 0x05, 0x07, 0x19, 0xe0, 0x29, 0xe7, 0x15, 0x00,
    0x25, 0x01, 0x75, 0x01, 0x95, 0x08, 0x81, 0x02, 0x95, 0x01, 0x75, 0x08, 0x81, 0x03, 0x95, 0x05,
    0x75, 0x01, 0x05, 0x08, 0x19, 0x01, 0x29, 0x05, 0x91, 0x02, 0x95, 0x01, 0x75, 0x03, 0x91, 0x03,
    0x95, 0x06, 0x75, 0x08, 0x15, 0x00, 0x25, 0x65, 0x05, 0x07, 0x19, 0x00, 0x29, 0x65, 0x81, 0x00,
    0xc0,
]

// NUL-terminated so the pointers can serve as C strings.
private let deviceNameBytes: [UInt8] = Array("SMK Keyboard".utf8) + [0]
private let manufacturerBytes: [UInt8] = Array("Swift".utf8) + [0]
private let serialNumberBytes: [UInt8] = Array("123456".utf8) + [0]

// Permanent (never-freed) storage for every buffer the HID/BLE stack keeps
// a pointer into past init — the Swift equivalent of the C original's
// `static const` arrays' process-lifetime storage.
private func blePermanentCopy(_ bytes: [UInt8]) -> UnsafeMutableBufferPointer<UInt8> {
    let storage = UnsafeMutableBufferPointer<UInt8>.allocate(capacity: bytes.count)
    _ = storage.initialize(from: bytes)
    return storage
}

// Set once by init_ble_hid(); read by start-advertising (device name, the
// advertised upload-service UUID).
private var deviceNameStorage: UnsafeMutableBufferPointer<UInt8>?
private var uploadSvcUuidStorage: UnsafeMutablePointer<ble_uuid128_t>?

// Single source of truth for the HID device handle — populated exactly
// once by init_ble_hid() below, directly from esp_hidd_dev_init()'s
// out-param. Typed OpaquePointer to match how ClangImporter imports
// `esp_hidd_dev_t *` (an opaque, forward-declared C struct).
private var hidDev: OpaquePointer? = nil

// esp_hidd_event_t values — pulled directly from the real,
// ClangImporter-imported enum (Bridging.h already `#include`s esp_hidd.h,
// so esp_hidd.h's declarations are visible to Swift as real types/values,
// not just C prototypes) rather than hand-copied integer literals. This
// gets header-derived values for free: if a future ESP-IDF upgrade
// reorders esp_hidd_event_t's cases, this recompiles to the new values
// automatically instead of silently keeping stale ones.
//
// (For the record, verified once against
// ~/.espressif/v6.0.1/esp-idf/components/esp_hid/include/esp_hidd.h
// during this task: START=0, CONNECT=1, PROTOCOL_MODE=2, CONTROL=3,
// OUTPUT=4, FEATURE=5, DISCONNECT=6, STOP=7 — notably NOT the task
// brief's draft placeholders of OUTPUT=2/DISCONNECT=3, which would have
// silently broken the reconnect-advertising path had they gone
// unverified.)
let espHiddStartEvent = ESP_HIDD_START_EVENT.rawValue
let espHiddConnectEvent = ESP_HIDD_CONNECT_EVENT.rawValue
let espHiddOutputEvent = ESP_HIDD_OUTPUT_EVENT.rawValue
let espHiddDisconnectEvent = ESP_HIDD_DISCONNECT_EVENT.rawValue

// Registered as esp_hidd_dev_init's `esp_event_handler_t callback` param —
// a plain Swift function passed as a @convention(c) value now that the
// registration call itself is Swift (no C forward declaration left, so no
// @_cdecl needed). The `base` param is esp_event_base_t (a const char *).
func bleHiddEventCallback(_ handlerArgs: UnsafeMutableRawPointer?, _ base: UnsafePointer<CChar>?, _ id: Int32, _ eventData: UnsafeMutableRawPointer?) {
    switch id {
    case espHiddStartEvent:
        kb_log("BLE HID Stack Started")
        startAdvertising()
    case espHiddConnectEvent:
        kb_log("BLE HID Connected")
    case espHiddOutputEvent:
        // Still fires: the report map keeps Report ID 1's LED output items
        // (`0x91 0x02` / `0x91 0x03`), so a host setting caps/num/scroll
        // lock lands here. This build simply has nothing to do with those —
        // there are no indicator LEDs wired up — and keymap upload no
        // longer arrives on a HID output report at all; it moved to the
        // custom GATT service below.
        break
    case espHiddDisconnectEvent:
        kb_log("BLE HID Disconnected")
        startAdvertising()
    default:
        break
    }
}

func send_keyboard_report(_ modifier: UInt8, _ keycodes: UnsafePointer<UInt8>) {
    guard let dev = hidDev, esp_hidd_dev_connected(dev) else { return }
    var report = [UInt8](repeating: 0, count: 8)
    report[0] = modifier
    // report[1] stays 0 (Reserved byte).
    for i in 0..<6 { report[2 + i] = keycodes[i] }
    // Map index 0, Report ID 1 (matches hidReportMapBytes above). Mutable
    // buffer pointer: esp_hidd_dev_input_set's real imported signature
    // takes non-const `uint8_t *data`.
    _ = report.withUnsafeMutableBufferPointer { esp_hidd_dev_input_set(dev, 0, 1, $0.baseAddress!, 8) }
}

// Reports a 0-100 battery level via the standard BLE Battery Service —
// esp_hidd_dev_init() already creates this GATT service internally as
// part of the HID-over-GATT profile, so this is the one call needed to
// feed it real data. Called from BatteryMonitor.swift, which owns the
// ADC-to-percentage math.
func smk_ble_set_battery_level(_ level: UInt8) {
    guard let dev = hidDev else { return }
    _ = esp_hidd_dev_battery_set(dev, level)
}

// Handed to esp_nimble_enable() by address (as a bare `void *`).
func ble_hid_host_task(_ param: UnsafeMutableRawPointer?) {
    kb_log("NimBLE Host Task Started")
    nimble_port_run()
    nimble_port_freertos_deinit()
}

// ---------------------------------------------------------------------------
// Custom keymap-upload GATT service (write packet in, notify response back)
// ---------------------------------------------------------------------------

private let smkUploadPacketLen = 32

// Value handle of the response characteristic, filled in by
// ble_gatts_add_svcs() during registration (NimBLE writes through the
// `val_handle` pointer in the characteristic definition) and used to
// address notifications back to the host. Permanent allocation so the
// pointer NimBLE holds stays valid for the life of the process.
private var uploadResponseHandle: UnsafeMutablePointer<UInt16>?

// Host writes a 32-byte upload packet; we dispatch it and notify the
// 32-byte reply. conn_handle comes in as an argument, so this needs no GAP
// callback of its own to know who to answer. Runs on the NimBLE host task;
// COMMIT writes NVS and briefly blocks the stack — same as the Report ID 2
// path this replaces.
private func smkUploadAccessCb(_ connHandle: UInt16, _ attrHandle: UInt16, _ ctxt: UnsafeMutablePointer<ble_gatt_access_ctxt>?, _ arg: UnsafeMutableRawPointer?) -> Int32 {
    guard let ctxt else { return Int32(BLE_ATT_ERR_UNLIKELY) }
    guard Int32(ctxt.pointee.op) == BLE_GATT_ACCESS_OP_WRITE_CHR else {
        return Int32(BLE_ATT_ERR_UNLIKELY)
    }

    var packet = [UInt8](repeating: 0, count: smkUploadPacketLen)
    var len: UInt16 = 0
    let flatOk = packet.withUnsafeMutableBufferPointer { buf in
        ble_hs_mbuf_to_flat(ctxt.pointee.om, buf.baseAddress!, UInt16(buf.count), &len) == 0
    }
    guard flatOk else { return Int32(BLE_ATT_ERR_UNLIKELY) }
    guard len == UInt16(smkUploadPacketLen) else { return Int32(BLE_ATT_ERR_INVALID_ATTR_VALUE_LEN) }

    var response = [UInt8](repeating: 0, count: smkUploadPacketLen)
    packet.withUnsafeBufferPointer { pkt in
        response.withUnsafeMutableBufferPointer { resp in
            smk_keymap_dispatch_packet(pkt.baseAddress!, resp.baseAddress!)
        }
    }

    let om = response.withUnsafeBufferPointer { resp in
        ble_hs_mbuf_from_flat(resp.baseAddress!, UInt16(resp.count))
    }
    guard let om else { return Int32(BLE_ATT_ERR_INSUFFICIENT_RES) }
    guard let handlePtr = uploadResponseHandle else { return Int32(BLE_ATT_ERR_UNLIKELY) }
    _ = ble_gatts_notify_custom(connHandle, handlePtr.pointee, om)
    return 0
}

// Builds the NULL-terminated ble_gatt_svc_def/ble_gatt_chr_def tables for
// the upload service through the imported NimBLE types, in permanent
// storage — NimBLE keeps these pointers past registration. The UUIDs come
// from Bridging.h's smk_ble_uuids.h import (generated constants); each is
// copied into permanent storage of its own since the header declares them
// `static const` per translation unit.
private func buildUploadServiceTable() -> UnsafePointer<ble_gatt_svc_def> {
    let svcUuid = UnsafeMutablePointer<ble_uuid128_t>.allocate(capacity: 1)
    svcUuid.pointee = smk_upload_svc_uuid
    uploadSvcUuidStorage = svcUuid
    let packetUuid = UnsafeMutablePointer<ble_uuid128_t>.allocate(capacity: 1)
    packetUuid.pointee = smk_upload_packet_chr_uuid
    let responseUuid = UnsafeMutablePointer<ble_uuid128_t>.allocate(capacity: 1)
    responseUuid.pointee = smk_upload_response_chr_uuid

    let responseHandle = UnsafeMutablePointer<UInt16>.allocate(capacity: 1)
    responseHandle.pointee = 0
    uploadResponseHandle = responseHandle

    let chrs = UnsafeMutablePointer<ble_gatt_chr_def>.allocate(capacity: 3)
    chrs[0] = ble_gatt_chr_def()
    chrs[0].uuid = UnsafeRawPointer(packetUuid).assumingMemoryBound(to: ble_uuid_t.self)
    chrs[0].access_cb = smkUploadAccessCb
    chrs[0].flags = ble_gatt_chr_flags(BLE_GATT_CHR_F_WRITE)
    chrs[1] = ble_gatt_chr_def()
    chrs[1].uuid = UnsafeRawPointer(responseUuid).assumingMemoryBound(to: ble_uuid_t.self)
    chrs[1].access_cb = smkUploadAccessCb
    chrs[1].flags = ble_gatt_chr_flags(BLE_GATT_CHR_F_NOTIFY)
    chrs[1].val_handle = responseHandle
    chrs[2] = ble_gatt_chr_def() // zeroed terminator

    let svcs = UnsafeMutablePointer<ble_gatt_svc_def>.allocate(capacity: 2)
    svcs[0] = ble_gatt_svc_def()
    svcs[0].type = UInt8(BLE_GATT_SVC_TYPE_PRIMARY)
    svcs[0].uuid = UnsafeRawPointer(svcUuid).assumingMemoryBound(to: ble_uuid_t.self)
    svcs[0].characteristics = UnsafePointer(chrs)
    svcs[1] = ble_gatt_svc_def() // zeroed terminator
    return UnsafePointer(svcs)
}

// ---------------------------------------------------------------------------
// Advertising + stack init (formerly ble_helper.c's start_advertising /
// init_ble_hid)
// ---------------------------------------------------------------------------

// Constructs `struct ble_hs_adv_fields` through the imported NimBLE type —
// its 1-bit presence flags are ClangImporter computed properties over the
// real header's bitfield layout. Called on stack start and on every
// disconnect. The upload service UUID goes in the *primary* advertisement
// so the configurator's scan filter matches it directly, without depending
// on how a host merges scan-response data; the name moves to the scan
// response — all three would overrun the 31-byte budget.
private func startAdvertising() {
    guard let nameStorage = deviceNameStorage, let namePtr = nameStorage.baseAddress,
          let svcUuid = uploadSvcUuidStorage else { return }
    let nameLen = nameStorage.count - 1 // trailing NUL not advertised

    var fields = ble_hs_adv_fields()
    fields.flags = UInt8(BLE_HS_ADV_F_DISC_GEN | BLE_HS_ADV_F_BREDR_UNSUP)
    fields.appearance = 0x03C1 // Keyboard
    fields.appearance_is_present = 1
    fields.uuids128 = UnsafePointer(svcUuid)
    fields.num_uuids128 = 1
    fields.uuids128_is_complete = 1

    guard ble_gap_adv_set_fields(&fields) == 0 else {
        kb_log("error setting advertisement data")
        return
    }

    var rspFields = ble_hs_adv_fields()
    rspFields.name = UnsafePointer(namePtr)
    rspFields.name_len = UInt8(nameLen)
    rspFields.name_is_complete = 1
    guard ble_gap_adv_rsp_set_fields(&rspFields) == 0 else {
        kb_log("error setting scan response data")
        return
    }

    var advParams = ble_gap_adv_params()
    advParams.conn_mode = UInt8(BLE_GAP_CONN_MODE_UND)
    advParams.disc_mode = UInt8(BLE_GAP_DISC_MODE_GEN)

    // own_addr_type 0 = BLE_OWN_ADDR_PUBLIC; BLE_HS_FOREVER is INT32_MAX
    // (host/ble_hs.h — a chained macro the importer doesn't surface, so the
    // value is spelled directly).
    guard ble_gap_adv_start(0, nil, Int32.max, &advParams, nil, nil) == 0 else {
        kb_log("error enabling advertisement")
        return
    }
    kb_log("Advertising started")
}

func init_ble_hid() {
    var ret = nvs_flash_init()
    if ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND {
        _ = nvs_flash_erase()
        ret = nvs_flash_init()
    }
    guard ret == ESP_OK else {
        // The C original ESP_ERROR_CHECK'd (abort) here; failing BLE init
        // but leaving the scan loop alive is the friendlier behavior.
        kb_log("nvs_flash_init failed; BLE disabled")
        return
    }

    // Must run before esp_hidd_dev_init(): esp_hidd_dev_init() synchronously
    // registers GATT services (GAP/GATT/DIS/BAS/HID) via NimBLE's
    // ble_gatts_count_cfg(), which — under CONFIG_BT_NIMBLE_STATIC_TO_DYNAMIC
    // (enabled in sdkconfig) — dereferences the host's dynamically-allocated
    // ble_hs_state_ctx. That allocation only happens inside ble_hs_init(),
    // called from nimble_port_init(). Calling esp_hidd_dev_init() first
    // dereferences a still-NULL ble_hs_state_ctx and crashes — found via
    // real hardware testing (Guru Meditation, Load access fault at 0x4,
    // inside ble_gatts_count_cfg <- ble_svc_gap_init <- esp_hidd_dev_init).
    guard nimble_port_init() == ESP_OK else {
        kb_log("nimble_port_init failed; BLE disabled")
        return
    }

    // Device config — imported esp_hid types, permanent backing storage for
    // everything the stack retains (see file header).
    let nameStorage = blePermanentCopy(deviceNameBytes)
    deviceNameStorage = nameStorage
    let manufacturerStorage = blePermanentCopy(manufacturerBytes)
    let serialStorage = blePermanentCopy(serialNumberBytes)
    let reportMapStorage = blePermanentCopy(hidReportMapBytes)

    let reportMaps = UnsafeMutablePointer<esp_hid_raw_report_map_t>.allocate(capacity: 1)
    reportMaps.pointee = esp_hid_raw_report_map_t()
    reportMaps.pointee.data = UnsafePointer(reportMapStorage.baseAddress)
    reportMaps.pointee.len = UInt16(reportMapStorage.count)

    var config = esp_hid_device_config_t()
    config.vendor_id = 0x16C0
    config.product_id = 0x05DF
    config.version = 0x0100
    config.device_name = UnsafeRawPointer(nameStorage.baseAddress!).assumingMemoryBound(to: CChar.self)
    config.manufacturer_name = UnsafeRawPointer(manufacturerStorage.baseAddress!).assumingMemoryBound(to: CChar.self)
    config.serial_number = UnsafeRawPointer(serialStorage.baseAddress!).assumingMemoryBound(to: CChar.self)
    config.report_maps = reportMaps
    config.report_maps_len = 1

    var dev: OpaquePointer? = nil
    guard esp_hidd_dev_init(&config, ESP_HID_TRANSPORT_BLE, bleHiddEventCallback, &dev) == ESP_OK, dev != nil else {
        kb_log("esp_hidd_dev_init failed; BLE disabled")
        return
    }
    hidDev = dev

    // Custom keymap-upload service. Registered here rather than as HID
    // Report ID 2 because macOS hides the HID service (0x1812) from Core
    // Bluetooth apps entirely. A registration failure is fatal (matching
    // the C original's ESP_ERROR_CHECK) rather than falling through to
    // advertise with the upload service silently missing or malformed.
    let uploadSvcs = buildUploadServiceTable()
    guard ble_gatts_count_cfg(uploadSvcs) == 0, ble_gatts_add_svcs(uploadSvcs) == 0 else {
        kb_log("upload GATT service registration failed")
        abort()
    }

    // Make the advertised/GATT device name match what startAdvertising()
    // broadcasts (esp_hidd_dev_init leaves the GAP service with the Kconfig
    // default name, e.g. "nimble").
    _ = ble_svc_gap_device_name_set(config.device_name)

    // Security: require encryption + bonding so macOS (and other hosts)
    // remember this keyboard and auto-reconnect after the first pairing,
    // instead of treating every reconnect as a brand-new device.
    //  - sm_io_cap = NO_IO: the board has no display/keypad for a passkey,
    //    so pairing is "Just Works" (no MITM protection).
    //  - sm_bonding = 1: actually persist the pairing instead of only
    //    encrypting for the current connection.
    //  - sm_our_key_dist / sm_their_key_dist include ID: exchanges the
    //    Identity Resolving Key, which is what lets the host resolve our
    //    address on later advertisements and reconnect silently rather than
    //    showing up as an unknown device each time.
    // (CONFIG_BT_NIMBLE_SM_LVL and CONFIG_BT_NIMBLE_NVS_PERSIST in sdkconfig
    // must also be enabled — see sdkconfig.defaults — for this to actually
    // take effect and survive a reboot.)
    //
    // ble_hs_cfg's sm_* flags are adjacent 1-bit bitfields; the imported
    // global's computed properties write them with header-derived packing.
    ble_hs_cfg.sm_io_cap = UInt8(BLE_SM_IO_CAP_NO_IO)
    ble_hs_cfg.sm_bonding = 1
    ble_hs_cfg.sm_mitm = 0
    ble_hs_cfg.sm_sc = 1
    ble_hs_cfg.sm_our_key_dist = UInt8(BLE_SM_PAIR_KEY_DIST_ENC | BLE_SM_PAIR_KEY_DIST_ID)
    ble_hs_cfg.sm_their_key_dist = UInt8(BLE_SM_PAIR_KEY_DIST_ENC | BLE_SM_PAIR_KEY_DIST_ID)

    // Enable the NimBLE stack (nimble_port_init() already ran above, before
    // esp_hidd_dev_init()). esp_nimble_enable takes the host task entry
    // point as a bare `void *`.
    let hostTask: @convention(c) (UnsafeMutableRawPointer?) -> Void = ble_hid_host_task
    _ = esp_nimble_enable(unsafeBitCast(hostTask, to: UnsafeMutableRawPointer.self))
}
